### ISSUE TITLE
Freeze development.

### ISSUE THREAD

**Issue by prostomarkeloff** [prostomarkeloff/Kitsul#2]
In this moment, current version of framework not maintaned. I thought about architecture and i decided to rewrite this.

**Comment by hioi** [comment]
![image](https://user-images.githubusercontent.com/34442450/66233427-04e47300-e6f4-11e9-9e2a-d7894cd223ce.png)

**Comment by prostomarkeloff** [comment]
You can check progress in "rewrite" branch.

**Comment by prostomarkeloff** [comment]
My simple check list for merge "rewrite" branch.

- [ ] Implement middlewares
- [ ] Implement websockets. It is really important.
- [ ] More customization! :)
